### ISSUE TITLE
Issues packaging cartographer_ros

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#4]
Ran into some warnings and a failure packaging cartographer_ros. I think the error will be due to the out-of-date tf2 package. But I'm opening this for visibility in case it isn't.

Build link: http://build.ros2.org/job/Rbin_uX64__cartographer_ros__ubuntu_xenial_amd64__binary/6/console#console-section-15

```
23:04:31 <command-line>:0:15: warning: ISO C++11 requires whitespace after the macro name
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc: In member function ‘std::unique_ptr<cartographer::transform::Rigid3<double> > cartographer_ros::TfBridge::LookupToTracking(cartographer::common::Time, const string&) const’:
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc:33:25: error: ‘durationFromSec’ is not a member of ‘tf2’
23:04:31    tf2::Duration timeout(tf2::durationFromSec(lookup_transform_timeout_sec_));
23:04:31                          ^
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc:51:17: error: ‘durationFromSec’ is not a member of ‘tf2’
23:04:31        timeout = tf2::durationFromSec(0.0);
23:04:31                  ^
23:04:31 make[4]: *** [CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o] Error 1
23:04:31 CMakeFiles/cartographer_ros.dir/build.make:281: recipe for target 'CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o' failed
23:04:31 make[4]: Leaving directory '/tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/obj-x86_64-linux-gnu'
23:04:31 make[3]: *** [CMakeFiles/cartographer_ros.dir/all] Error 2
23:04:31 make[2]: *** [all] Error 2
23:04:31 CMakeFiles/Makefile2:235: recipe for target 'CMakeFiles/cartographer_ros.dir/all' failed
```

Additionally there's a block of warnings that we should make sure are all chill or determine if we need to update dependencies. @clalancette do we need any of the stuff listed below?

```
23:02:28 -- Checking for module 'libopenni2'
23:02:28 --   No package 'libopenni2' found
23:02:28 -- Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS) 
23:02:28 ** WARNING ** io features related to openni2 will be disabled
23:02:28 ** WARNING ** io features related to pcap will be disabled
23:02:28 ** WARNING ** io features related to png will be disabled
23:02:28 -- The imported target "vtkRenderingPythonTkWidgets" references the file
23:02:28    "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
23:02:28 but this file does not exist.  Possible reasons include:
23:02:28 * The file was deleted, renamed, or moved to another location.
23:02:28 * An install or uninstall procedure did not complete successfully.
23:02:28 * The installation package was faulty and contained
23:02:28    "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
23:02:28 but not all the files it references.
23:02:28 
23:02:28 -- The imported target "vtk" references the file
23:02:28    "/usr/bin/vtk"
23:02:28 but this file does not exist.  Possible reasons include:
23:02:28 * The file was deleted, renamed, or moved to another location.
23:02:28 * An install or uninstall procedure did not complete successfully.
23:02:28 * The installation package was faulty and contained
23:02:28    "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
23:02:28 but not all the files it references.
23:02:28 
23:02:29 -- LIBUSB_1_LIBRARY (missing:  LIBUSB_1_INCLUDE_DIR) 
23:02:29 ** WARNING ** io features related to libusb-1.0 will be disabled
```

**Comment by dhood** [comment]
Yeah, you're correct. it requires this pr from TF2 now:
https://github.com/ros2/geometry2/pull/16

On 18 Jun. 2017 04:42, "Steven! Ragnarök" <notifications@github.com> wrote:

Ran into some warnings and a failure packaging cartographer_ros. I think
the error will be due to the out-of-date tf2 package. But I'm opening this
for visibility in case it isn't.

Build link: http://build.ros2.org/job/Rbin_uX64__cartographer_ros__
ubuntu_xenial_amd64__binary/6/console#console-section-15

23:04:31 <command-line>:0:15: warning: ISO C++11 requires whitespace
after the macro name
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc:
In member function
‘std::unique_ptr<cartographer::transform::Rigid3<double> >
cartographer_ros::TfBridge::LookupToTracking(cartographer::common::Time,
const string&) const’:
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc:33:25:
error: ‘durationFromSec’ is not a member of ‘tf2’
23:04:31    tf2::Duration
timeout(tf2::durationFromSec(lookup_transform_timeout_sec_));
23:04:31                          ^
23:04:31 /tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/cartographer_ros/tf_bridge.cc:51:17:
error: ‘durationFromSec’ is not a member of ‘tf2’
23:04:31        timeout = tf2::durationFromSec(0.0);
23:04:31                  ^
23:04:31 make[4]: ***
[CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o]
Error 1
23:04:31 CMakeFiles/cartographer_ros.dir/build.make:281: recipe for
target 'CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o'
failed
23:04:31 make[4]: Leaving directory
'/tmp/binarydeb/ros-r2b2-cartographer-ros-0.1.0/obj-x86_64-linux-gnu'
23:04:31 make[3]: *** [CMakeFiles/cartographer_ros.dir/all] Error 2
23:04:31 make[2]: *** [all] Error 2
23:04:31 CMakeFiles/Makefile2:235: recipe for target
'CMakeFiles/cartographer_ros.dir/all' failed

Additionally there's a block of warnings that we should make sure are all
chill or determine if we need to update dependencies. @clalancette
<https://github.com/clalancette> do we need any of the stuff listed below?

23:02:28 -- Checking for module 'libopenni2'
23:02:28 --   No package 'libopenni2' found
23:02:28 -- Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY
OPENNI2_INCLUDE_DIRS)
23:02:28 ** WARNING ** io features related to openni2 will be disabled
23:02:28 ** WARNING ** io features related to pcap will be disabled
23:02:28 ** WARNING ** io features related to png will be disabled
23:02:28 -- The imported target "vtkRenderingPythonTkWidgets"
references the file
23:02:28    "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
23:02:28 but this file does not exist.  Possible reasons include:
23:02:28 * The file was deleted, renamed, or moved to another location.
23:02:28 * An install or uninstall procedure did not complete successfully.
23:02:28 * The installation package was faulty and contained
23:02:28    "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
23:02:28 but not all the files it references.
23:02:28
23:02:28 -- The imported target "vtk" references the file
23:02:28    "/usr/bin/vtk"
23:02:28 but this file does not exist.  Possible reasons include:
23:02:28 * The file was deleted, renamed, or moved to another location.
23:02:28 * An install or uninstall procedure did not complete successfully.
23:02:28 * The installation package was faulty and contained
23:02:28    "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
23:02:28 but not all the files it references.
23:02:28
23:02:29 -- LIBUSB_1_LIBRARY (missing:  LIBUSB_1_INCLUDE_DIR)
23:02:29 ** WARNING ** io features related to libusb-1.0 will be disabled

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros2/rosdistro/issues/4>, or mute the thread

**Comment by nuclearsandwich** [comment]
updated geometry2 packages have been released and are pending build.

**Comment by mikaelarguedas** [comment]
The tf2 needs repackaging as you figured it out.

I remember seeing the same warnings about openni2 when building cartographer_ros but it was not a required dep, I think that's why it's not in the package.xml (I think the same applies to libusb).
Not sure about the VTK one though

**Comment by nuclearsandwich** [comment]
It's [happier](http://build.ros2.org/job/Rbin_uX64__cartographer_ros__ubuntu_xenial_amd64__binary/7/) with the new tf2 packages. I'll close this for now but do give a shout if any of those optional dependencies should made available.

**Comment by clalancette** [comment]
@nuclearsandwich Sorry for the late reply.  Basically, no, I don't think we need any of those features, so I think the package should be good as-is.  Thanks for checking, though.
